<?php

$pets = [
    "nummer1" => "Griffioen",
    "nummer2" => "Draak",
    "nummer3" => "Eenhoorn",
    "nummer4" => "BigFoot"
];

foreach ($pets as $key => $value) {
    echo $key . ": " . $value . "<br>";
}
?>
<?php 
echo "<br>---------------------------------------------------<br>";
echo "<i>The above output is generated by the code below:</i><br>";
highlight_file(__FILE__);
?>