<?php

for ($i = 10; $i > 0; $i--) {
    echo $i;

    if ($i > 1) {
        echo ", ";
    }
}

echo "<br><br>";
echo "<i>The above output is generated by the code below:</i><br>";
highlight_file( __FILE__ ); 