<?php

// Case 1: == en ====
$int1 = 1;
$str1 = "1";

echo "case 1: check 1 vs \"1\" met == en === <br><br>";

if ($int1 == $str1) {
    echo "Met == zijn 1 en \"1\" gelijk, omdat alleen de waarde wordt vergeleken.<br>";
}

if ($int1 === $str1) {
    echo "Met === zijn 1 en \"1\" gelijk, de datatypes zijn gelijk.<br><br>";
} else {
    echo "Met === zijn 1 en \"1\" niet gelijk, de datatypes zijn niet gelijk.<br><br>";
}


// Case 2: &&
echo "case 2: check && door te kijken of ik mag autorijden<br><br>";
$leeftijd = 25;
$heeftRijbewijs = true;

if ($leeftijd >= 18 && $heeftRijbewijs) {
    echo "Ouder dan 18 jaar én heeft zijn rijbewijs, dus ik mag autorijden.<br><br>";
}else{
    echo "Mag geen autorijden.<br><br>";
}

// Case 3: ||
echo "case 3: check || door te kijken of ik aan het werk ben<br><br>";

$werktThuis = true;
$werktOpKantoor = false;

if ($werktThuis || $werktOpKantoor) {
    echo "Werkt thuis of op kantoor, dus is aan het werk.<br>";
} else {
    echo "Werkt niet thuis en niet op kantoor.<br>";
}

echo "<br>---------------------------------------------------<br>";
echo "<i>The above output is generated by the code below:</i><br>";
highlight_file( __FILE__ ); 
?>