<?php
//POST VOOR FORM!
$keuze = "";
$tekst = "";

//als er iets via GET is verstuurd
if ($_POST) {

    $keuze = $_POST["dier"];

    //kijk welke keuze is gemaakt
    switch ($keuze) {

        case "hond":
            $tekst = "Je hebt een hond gekozen.";
            break;

        case "kat":
            $tekst = "Je hebt een kat gekozen.";
            break;

        case "papegaai":
            $tekst = "Je hebt een papegaai gekozen.";
            break;

        default:
            $tekst = "Onbekende keuze.";
    }
}

?>

<!DOCTYPE html>
<html>

<head>
    <title>Switch demo</title>
</head>

<body>

    <!-- simpel keuzeformulier -->
    <form method="POST">
        <!-- //POST VOOR FORM! -->
        <select name="dier">
            <option value="hond">Hond</option>
            <option value="kat">Kat</option>
            <option value="papegaai">Papegaai</option>
        </select>

        <button type="submit">Kies</button>

    </form>

    <?php
    //toont resultaat pas na een keuze
    echo $tekst;
    ?>
</body>

<?php 
echo "<br>---------------------------------------------------<br>";
echo "<i>The above output is generated by the code below:</i><br>";
highlight_file(__FILE__);
?>
</html>