<?php 

$sum=0;
$n=100;
for ($i=0; $i<=$n; $i++){
	$sum+=$i+($n-$i);
};
echo $sum/2;

echo "<br>"; 
echo 'uitleg: begin met i=0 en loop tot i=n<br>';
echo 'iedere iteratie: tel steeds i en n-i op en tel die op bij de total sum: 0+100, 1+99, 2+98 etc. (tot i == n)<br>';
echo 'dan total sum halveren';

echo "<br><br>";
echo "<i>The above output is generated by the code below:</i><br>";
highlight_file( __FILE__ ); 
?>

