<?php

$sum = 0;
$begin = 0;
$end = 100;

//haal begin en eind uit formulier
if ($_GET) {
	$begin = $_GET["begin"];
	$end = $_GET["end"];
}

//check of begin niet groter is dan eind
if ($begin < $end) {
	//gauss manier
	$sum = 0;
	$n = 100;
	for ($i = 0; $i <= $n; $i++) {
		$sum += $i + ($n - $i);
	};
	$sum = $sum / 2;
	$output = "De som van " . $begin . " t/m " . $end . " is " . $sum;
} else {
	$output = "Begin moet kleiner zijn dan eind.";
}

?>

<html>

<body>

	<form method="GET">
		
		Begin:
		<input type="number" name="begin" value="<?php echo $begin; ?>">
		
		Eind:
		<input type="number" name="end" value="<?php echo $end; ?>">

		<button type="submit">Bereken</button>

	</form>

	<br>

	<?php

	echo $output;

	echo "<br><br>";

	echo "uitleg: begin met i = begin en loop tot i = eind<br>";
	echo "iedere iteratie: tel steeds i en begin + eind - i op<br>";
	echo "bijvoorbeeld: " . $begin . "+" . $end . ", " .
		($begin + 1) . "+" . ($end - 1) . ", enz.<br>";
	echo "dan total sum halveren";

	echo "<br><br>";
	echo "<i>The above output is generated by the code below:</i><br>";
	highlight_file(__FILE__);

	?>

</body>

</html>

<?php
echo "<br><br>";
echo "<i>The above output is generated by the code below:</i><br>";
highlight_file(__FILE__);
?>