<?php

$a = 5;

//postfix, dus eerst 5 printen en daarna +1
echo $a++;
echo "<br>";

//$a is nu 6
echo $a;

echo "<br><br>";

$b = 10;

//$b staat buiten de functie en bestaat hier dus niet automatisch
// function scopeTest() {
//     echo $b;
// }

// scopeTest();

echo "<br><br>";
echo "<i>The above output is generated by the code below:</i><br>";
highlight_file(__FILE__);

?>