<?php

//! Uit de uitwerkingen gehaald om te checken hoe die werkt.

class Model1 { 
    public $text; 
     
    public function __construct() { 
        $this->text = 'Hello world!'; 
    }         
} 

class View1 { 
    private $model; 
    private $controller; 
     
    public function __construct(Controller1 $controller, Model1 $model) { 
        $this->controller = $controller; 
        $this->model = $model; 
    } 
     
    public function output() { 
        return '<h1>' . $this->model->text .'</h1>'; 
    } 
     
} 

class Controller1 { 
    private $model; 

    public function __construct(Model1 $model) { 
        $this->model = $model; 
    } 
} 



//initiate the triad 
$model = new Model1(); 
//It is important that the controller and the view share the model 
$controller = new Controller1($model); 
$view = new View1($controller, $model); 
echo $view->output();

echo "<br><br>";
echo "<i>The above output is generated by the code below:</i><br>";
highlight_file( __FILE__ ); 
?>