<?php 

//! Uit de uitwerkingen gehaald om te checken hoe die werkt.

class Model2 { 
    public $text; 
     
    public function __construct() { 
        $this->text = 'Hello world!'; 
    }         
} 

class View2 { 
    private $model; 
    private $controller; 
     
    public function __construct(Controller2 $controller, Model2 $model) { 
        $this->controller = $controller; 
        $this->model = $model; 
    } 
     
    public function output() { 
        return '<a href="class_mvc2.php?action=textclicked">' . $this->model->text . '</a>'; 
    } 
     
} 

class Controller2 { 
    private $model; 

    public function __construct(Model2 $model) { 
        $this->model = $model; 
    } 

    public function textClicked() { 
        $this->model->text = 'Text Updated'; 
    } 
} 


$model = new Model2(); 
//It is important that the controller and the view share the model 
$controller = new Controller2($model); 
$view = new View2($controller, $model); 
if (isset($_GET['action'])) {
    $controller->{$_GET['action']}(); 
}
echo $view->output(); 

echo "<br><br>";
echo "<i>The above output is generated by the code below:</i><br>";
highlight_file( __FILE__ ); 
?> 