<?php

echo "<h2>Pass by value</h2>";

function changeValue($number) {
    $number = 10;
}

$number = 5;

echo "Voor de functie: " . $number . "<br>";

changeValue($number);

echo "Na de functie: " . $number . "<br>";
echo "De originele variabele ongewijzigd<br>";




echo "<h2>Pass by reference</h2>";

function changeReference(&$number) {
    $number = 10;
}

$number = 5;

echo "Voor de functie: " . $number . "<br>";

changeReference($number);

echo "Na de functie: " . $number . "<br>";
echo "Met & wordt originele variabele gewijzigd<br>";


echo "<h2>Object / class</h2>";

class Person {

    public string $name;

    function __construct($name) {
        $this->name = $name;
    }
}

function changePerson($person) { //zonder &
    $person->name = "Piet";
}

$person = new Person("Ben");

echo "Voor de functie: " . $person->name . "<br>";

changePerson($person);

echo "Na de functie: " . $person->name . "<br>";
echo "Bij een object wordt hetzelfde object aangepast, ook zonder &.<br>";


?>
<?php 
echo "<br>---------------------------------------------------<br>";
echo "<i>The above output is generated by the code below:</i><br>";
highlight_file(__FILE__);
?>
